;;; -*- mode: Lisp; Syntax: Common-Lisp; -*-
;;;
;;; Copyright (c) 2025 by the authors.
;;;
;;; See LICENCE for details.

(in-package :hu.dwim.genassem/x86.test)

(in-suite test)

(defsuite* infra)

(deftest register-lookup ()
  (mapcar (lambda (el)
            (is (equal (second el)
                       (multiple-value-list
                        (decode-register (first el) :gr8)))))
          '((al   (0 8 ()))
            (bl   (3 8 ()))
            (r13b (5 8 1))
            (r8b  (0 8 1))
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (multiple-value-list
                        (decode-register (first el) :gr16)))))
          '((bx   (3 16 ()))
            (r13w (5 16 1))
            (si   (6 16 ()))
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (multiple-value-list
                        (decode-register (first el) :gr32)))))
          '((eax  (0 32 ()))
            (edx  (2 32 ()))
            (r11d (3 32 1))
            (esi  (6 32 ()))
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (multiple-value-list
                        (decode-register (first el) :gr64)))))
          '((rax  (0 64 ()))
            (r8   (0 64 1))
            (r15  (7 64 1))
            (rsi  (6 64 ()))
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (decode-register (first el) :|RSTi|))))
          '((st0  0)
            (st3  3)
            (st7  7)
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (decode-register (first el) :vr64))))
          '((mm0  0)
            (mm3  3)
            (mm7  7)
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (decode-register (first el) :vr128))))
          '((xmm0  0)
            (xmm3  3)
            (xmm7  7)
            (xmm15 15)
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (decode-register (first el) :vr256))))
          '((ymm0  0)
            (ymm3  3)
            (ymm7  7)
            (ymm15 15)
            ))
  (mapcar (lambda (el)
            (is (equal (second el)
                       (decode-register (first el) :vr512))))
          '((zmm0  0)
            (zmm3  3)
            (zmm7  7)
            (zmm15 15)
            ))
  (values))
